version: "2"
services:
  nginx-proxy:
    container_name: nginx-proxy
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /root/web-docker/nginx/conf.d:/etc/nginx/conf.d
      - ./uploadsize.conf:/etc/nginx/conf.d/uploadsize.conf:ro
      - /root/web-docker/nginx/vhost.d:/etc/nginx/vhost.d
      - /root/web-docker/nginx/dhparam:/etc/nginx/dhparam
      - /root/web-docker/nginx/certs:/etc/nginx/certs:ro
      - /root/web-docker/nginx/html:/usr/share/nginx/html
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - /root/web-docker/nginx/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-proxy
  db:
    image: mariadb:latest
    restart: always
    volumes: 
      - /root/web-docker/mariadb/mysql:/var/lib/mysql
    env_file:
      - mysql.env
      - mysql_nextcloud.env
  nextcloud:
    image: nextcloud
    restart: always
    depends_on:
      - db
    expose:
      - 80
    links:
      - db
    volumes:
      - /root/web-docker/nextcloud/var_www_html:/var/www/html
      - /root/web-docker/nextcloud/data:/var/www/html/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - MYSQL_HOST=db
      - VIRTUAL_PORT=80
    env_file:
      - nextcloud.env
      - mysql_nextcloud.env
  mumble:
    image: phlak/mumble
    restart: always
    ports:
      - "64738:64738"
      - "10025:64738"
      - "64738:64738/udp"
    volumes:
      - /root/web-docker/mumble:/etc/mumble
    env_file:
      - mumble.env
